### PR TITLE
Add 'isNew' method on Entity to see if saved

### PR DESCRIPTION
**Pull request by vlucas**
- Add Mapper::build method to build a new entity but not save it
- Change Mapper::create method so Entity object is returned on success
- Add tests for changes around build, create, and isNew

### CODE REVIEW

**Comment by vlucas** [comment]
Needs review @psamatt @pnomolos

**Comment by psamatt** [comment]
@vlucas Great work, nice addition!! On top of the unit tests you've added, I think we need to add additional assertions to existing tests / create new tests to make sure when you get an object from the datasource using `first()` or `all()`, then `$entity->isNew()` returns `false`. Thoughts?

**Comment by vlucas** [comment]
The `first()` and `all()` methods both use the mapper's `collection()` method, which is where I am ensuring `isNew` is `false`. The insert test that uses `$mapper->get()` internally uses `first`, and has test coverage, so we should be good.

**Comment by psamatt** [comment]
Looks good to me - merged :+1:

**Pull request merged**
