### PR TITLE
Functional methods

### PR DESCRIPTION
**Pull request by pnomolos**
Something else I began working on today, not sure if you're wanting something like this in core.  I just thought it'd be handy because right now there's no easy way to run a map function across the entire collection (`array_map($func, $query->execute->toArray())` _isn't_ synonymous to what this does)

### CODE REVIEW

**Comment by vlucas** [comment]
If these methods can work on the entity collection object, I would rather them be there. Will they work there the same way? My hesitation is that these are not directly related to the query, but are instead performing operations on the already retrieved collection, so they should be there in order to keep everything within it's own realm of concerns.

**Comment by pnomolos** [comment]
That was my intention, maybe add some pass-through methods on Query so you can do stuff like `$mapper->all('Entity_Post')->map()` without having to add an execute in between?

**Comment by vlucas** [comment]
Yeah. Perhaps we should change `__call` to assume a pass-through to the Collection object if no custom method is registered instead of throwing an exception. If we do that, we could probably also get rid of the `toArray` helper pass-through and just move that code up to `__call`.

**Comment by pnomolos** [comment]
Just updated this so the methods are now on `Collection` and `Query::__call` check to see if it can pass through.  I'm wondering, however, do we want to whitelist methods rather than passing everything through?

**Pull request merged**
