### PR TITLE
*Delete methods

### PR DESCRIPTION
**Pull request by pnomolos**
I still need to write tests for these, but how do they look?

### CODE REVIEW

**Comment by vlucas** [comment]
I think maybe `beforeDeleteConditions` and `afterDeleteConditions` will work. I added all the before\* and after\* instance methods into Spot now: c1078b7ed5531321f6ae7f70c741d03c0a72dcc8

**Comment by vlucas** [comment]
Whoops - did not mean to close :)

**Comment by pnomolos** [comment]
OK, this is now updated :)  One concern, though, is that developers may just end up having the instance beforeDelete and afterDelete methods point to the static methods anyway (because you'll often have to run the same code).

**Comment by pnomolos** [comment]
Also, what are your thoughts on passing `$conditions[0]['conditions']` (so the original conditions passed in) rather than array that's passed to the connection directly?

**Comment by vlucas** [comment]
I do think the original method conditions should be passed in, as-is. It should make them easier to parse.

**Comment by pnomolos** [comment]
OK, I'm going to write the tests for these now ... not exactly sure where they should go, though.  `CRUD.php`?  `Entity.php`?  A new `Events.php`?

**Comment by vlucas** [comment]
A new Events.php sounds great. I will expand it with more test coverage as
well after merging.

On Thursday, November 15, 2012, pnomolos wrote:

> OK, I'm going to write the tests for these now ... not exactly sure where
> they should go, though. CRUD.php? Entity.php? A new Events.php?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vlucas/Spot/pull/17#issuecomment-10429912.

## 

## 

Vance Lucas
http://vancelucas.com
(405) 303-1021

**Comment by pnomolos** [comment]
I'm deleting this request as I moved things into a separate branch and will re-open.

**Pull request closed without merging**
