### PR TITLE
Add Sqlite adapter

### PR DESCRIPTION
**Pull request by psamatt**
I've added a second adapter to allow users to be able to use Sqlite databases instead of MySQL.

Updated README file to accomodate new connection method

### CODE REVIEW

**Comment by vlucas** [comment]
SQLite is a great addition - especially for testing. I will have to test this out locally before merging as it adds a whole new db type.

**Comment by vlucas** [comment]
Two things I see missing:
1) A new `phpunit_sqlite.xml` config file
2) Updated `.travis.yml` with SQLite config so the SQLite tests will get run with every change as well.

**Comment by psamatt** [comment]
Hi Vance, 

I've added the new phpunit_sqlite.xml config file and adjustments to .travis.yml as mentioned. 

I've got all the tests passing apart from one that i've had to skip as Sqlite doesnt support SQL queries that have a 'having' condition without a 'group by' like MySQL does. I first checked Doctrine to see how this handles this condition with the exact same query and that throws a PDO Exception, so skipping the test if the adapter is Sqlite is the only way to handle this case.

**Comment by vlucas** [comment]
Looks good to me - thanks for the addition! :+1:

**Pull request merged**
