### PR TITLE
Integer fix

### PR DESCRIPTION
**Pull request by pnomolos**
This also includes a fix for isModified - fields set to NULL return false for `isset` so I used `array_key_exists` instead.

### CODE REVIEW

**Comment by pnomolos** [comment]
A follow-up to this.  Should setting an Integer field to '' be cast to 0 or set to NULL?  I'm running into this issue when passing $_POST data...

**Comment by vlucas** [comment]
To me, an empty string is the same as NULL - It's no value.

**Comment by pnomolos** [comment]
Would you feel comfortable then having it cast an empty string to a NULL?

**Comment by vlucas** [comment]
Yes, that's fine with me

**Comment by vlucas** [comment]
Merged with a cherry-pick due to issues with merge and rebase.
SHA1: eb53bae6998c9e7bc9941b1ed4aa8febdc48c19c

**Pull request closed without merging**
