### PR TITLE
Data tweaks and DateTime updates.

### PR DESCRIPTION
**Pull request by pnomolos**
Trying to get into the flow of a separate branch for all the "types" of different work I'm doing, but not there yet so this has the Datetime changes as well as some additions for working with an Entity and checking for modified vs. unmodified data.

### CODE REVIEW

**Comment by vlucas** [comment]
I like these fixes, but instead of a new public API method on `Spot\Entity` called `fieldModified` I'd like to see it rolled into `dataModified` where if you specify a field name, it returns the data for only that field or else boolean false if it's not set. You could also apply the same single-field code to `dataUnmodified` to make the behavior consistent.

**Comment by pnomolos** [comment]
Kept `fieldModified` and updated `dataModified` and `dataUnmodified` because there was the possibility of edge-cases where the data\* methods could return boolean false even with the field set.

**Comment by vlucas** [comment]
Good call on the `data*` methods and boolean edge cases. Null is the default value for "no value" and still evaluates to false if a user needs to use it that way.

I still don't like the `fieldModified` method though because it doesn't indicate a boolean will be returned - perhaps we can rename it to `isModified` and expand its use to seeing if anything on the Entity object has been modified if no field name is passed in as the first argument? Just trying to minimize the public API on Entity objects to keep them lightweight.

**Comment by vlucas** [comment]
Okay, some good changes here. Just a few style nitpicks:
- Opening curly brace needs to be on a new line (PSR-2 coding standards)
- Method needs at least a small docblock comment saying what it does

Also, return something like `return count($this->_dataModified) > 0;` instead of the array_keys stuff - it's just a little more clear what you're trying to accomplish.

**Comment by pnomolos** [comment]
I used `!!count($this->_dataModified);` as it should be clear enough and is faster than doing a numerical comparison :)

**Pull request merged**
