### PR TITLE
Condition reset

### PR DESCRIPTION
**Pull request by pnomolos**
Beginning of the reset and snapshot functionality.  Does not yet auto-reset on iterator and doesn't snapshot after Relation objects are created.  Wanted to get some thoughts on how it looks right now.

### CODE REVIEW

**Comment by pnomolos** [comment]
Oh, this got all confused now :(  Should I close this and re-open it but base it off of your current master (will that work?)

**Comment by vlucas** [comment]
I am actually not sure how to update or re-open pull requests. You can update the code and push and see what happens. As for the rebase, you should be able to `git rebase origin/master` assuming `origin` is this git repository, not your own fork.

**Comment by vlucas** [comment]
Seems like you can just push to the same branch again:
http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review

**Comment by pnomolos** [comment]
OK, I'll update it to be based off your master rather than my master and re-push

**Comment by vlucas** [comment]
I can't merge it in if you close it :) :+1:

**Comment by pnomolos** [comment]
I know - that's why I opened another merge request (I thought, at least) :+1:

**Comment by pnomolos** [comment]
Yeah, new one is right here: https://github.com/vlucas/Spot/pull/24

**Pull request closed without merging**
